project_name: original
project_slug: original
portal:
  name: Банкетам.Нет
  tagline: Бронирование помещений для проведения банкетов
admin:
  login: Admin26
  password: Demo20
brand:
  primary: '#FFFDD0'
  dark: '#006400 '
  accent: '#FFDAB9'
main:
  label: Заявка
  code: Booking
  table: bookings
  fields:
    - column: room_type
      go_name: RoomType
      label: Тип помещения
      type: enum
      widget: select
      options:
        - value: зал
          label: Зал
        - value: ресторан
          label: Ресторан
        - value: лентняя веранда
          label: Летняя веранда
        - value: закрытая веранда
          label: Закрытая веранда
      required: true
    - column: start_date
      go_name: StartDate
      label: Дата начала банкета
      type: date
      widget: date
      options: []
      required: true
    - column: payment_method
      go_name: PaymentMethod
      label: Способ оплаты
      type: enum
      widget: select
      options:
        - value: наличные
          label: Наличные
        - value: банковская карта
          label: Банковская карта
        - value: безналичный расчёт
          label: Безналичный расчёт
      required: true
  statuses:
    - Новая
    - Банкет назначен
    - Банкет завершен
reviews: true
pages:
  login: true
  register: true
  create_form: true
  cabinet: true
  admin: true
  slider: true
